//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeropuertos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aeropuertos()
        {
            this.PuertasDeAbordajes = new HashSet<PuertasDeAbordajes>();
        }
    
        public long IDAeropuerto { get; set; }
        public string Cuidad { get; set; }
        public string Pais { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuertasDeAbordajes> PuertasDeAbordajes { get; set; }
    }
}
