//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Itinerarios()
        {
            this.AsientosDeItinerarios = new HashSet<AsientosDeItinerarios>();
        }
    
        public long IDItinerario { get; set; }
        public bool Estado { get; set; }
        public System.DateTime HoraRealDeSalida { get; set; }
        public System.DateTime HoraRealDeLlegada { get; set; }
        public long IDVuelo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsientosDeItinerarios> AsientosDeItinerarios { get; set; }
        public virtual Vuelos Vuelos { get; set; }
    }
}
