//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maletas
    {
        public long IDMaleta { get; set; }
        public decimal Peso { get; set; }
        public string CodigoAsignado { get; set; }
        public bool Fragil { get; set; }
        public bool Extra { get; set; }
        public long IDAsientoDeItinerario { get; set; }
    
        public virtual AsientosDeItinerarios AsientosDeItinerarios { get; set; }
    }
}
