//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuertasDeAbordajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PuertasDeAbordajes()
        {
            this.Vuelos = new HashSet<Vuelos>();
        }
    
        public long IDPuertaDeAbordaje { get; set; }
        public string Codigo { get; set; }
        public bool EstadoActual { get; set; }
        public short Terminal { get; set; }
        public short NumeroDePuerta { get; set; }
        public bool Estado { get; set; }
        public long IDAeropuerto { get; set; }
    
        public virtual Aeropuertos Aeropuertos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vuelos> Vuelos { get; set; }
    }
}
