//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vuelos()
        {
            this.AsientosDeVuelos = new HashSet<AsientosDeVuelos>();
            this.Itinerarios = new HashSet<Itinerarios>();
        }
    
        public long IDVuelo { get; set; }
        public string Codigo { get; set; }
        public string TipoDeAvion { get; set; }
        public System.DateTime HoraDeSalida { get; set; }
        public System.DateTime HoraDeLlegada { get; set; }
        public bool Estado { get; set; }
        public long IDAerolinea { get; set; }
        public long IDPuertaDeAbordaje { get; set; }
    
        public virtual Aerolineas Aerolineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsientosDeVuelos> AsientosDeVuelos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itinerarios> Itinerarios { get; set; }
        public virtual PuertasDeAbordajes PuertasDeAbordajes { get; set; }
    }
}
